### ISSUE TITLE
AttributeError: type object 'QMessageBox' has no attribute 'Question'.

### ISSUE THREAD

**Issue by ergonap** [doitsujin/ffxiv-benchmark-launcher#2]
Could this be my install? I have nothing to go off, I'm not the most knowledgeable linux person, but...I tried to set up like this. Fresh python3 and pip install of pyqt6. Full AMD setup, Ubuntu 22.04.

![image](https://github.com/doitsujin/ffxiv-benchmark-launcher/assets/833025/e8e11eec-47a5-48f8-a67e-d28290c39edc)
I downloaded the windows benchmark and unzipped it to /home/bsmt/Desktop/FFXIV which is where the .exe resides.
However, what I'm seeing in console is: 

`python3 ffxiv-benchmark.py 
Traceback (most recent call last):
  File "/home/bsmt/Desktop/FFXIV/ffxiv-benchmark.py", line 677, in launch_benchmark
    self.launch(self.build_cmdline(False))
  File "/home/bsmt/Desktop/FFXIV/ffxiv-benchmark.py", line 700, in launch
    msg.setIcon(QMessageBox.Question)
AttributeError: type object 'QMessageBox' has no attribute 'Question'. Did you mean: 'question'?
Traceback (most recent call last):
  File "/home/bsmt/Desktop/FFXIV/ffxiv-benchmark.py", line 682, in launch_character_creation
    self.launch(cmdline)
  File "/home/bsmt/Desktop/FFXIV/ffxiv-benchmark.py", line 700, in launch
    msg.setIcon(QMessageBox.Question)
AttributeError: type object 'QMessageBox' has no attribute 'Question'. Did you mean: 'question'?
`

**Comment by 4ltc0de** [comment]
Looks to be an issue with the update to PyQt6, so any references in the script should be changed from
- `QMessageBox.Question` to `QMessageBox.Icon.Question`
- `QMessageBox.Warning` to `QMessageBox.Icon.Warning`
- `QMessageBox.Critical` to `QMessageBox.Icon.Critical`
- `QMessageBox.Yes` to `QMessageBox.StandardButton.Yes`
- `QMessageBox.No` to `QMessageBox.StandardButton.No`
- `QMessageBox.Ok` to `QMessageBox.StandardButton.Ok`

**Comment by mihawk90** [comment]
Submitting a patch right now

edit:
Have fun - https://github.com/doitsujin/ffxiv-benchmark-launcher/blob/f513877355c1c3c6b4659dec5dfa1b0b1d3e12d7/ffxiv-benchmark.py

**Comment by ergonap** [comment]
tested; can confirm I can get it to run with  @mihawk90 's  patch
