### ISSUE TITLE
elf_search_auxv can't find symbol in module / Unable to launch application Error

### ISSUE THREAD

**Issue by MjAdrian** [doitsujin/ffxiv-benchmark-launcher#4]
Hello, I am having an issue when trying to start the test bench. I am somewhat familiar with Linux, been using it for about a year. But relatively new to using Wine, mostly because of FFXIV. I have the game downloaded through the XIV Launcher Flatpak version. When I try to start the benchmark I get a few errors. I am not entirely sure what could be causing it (I believe the issue might be because I am missing something in wine) so any help is greatly appreciated.  

When I click start, this pop-up error appears. 
![image](https://github.com/doitsujin/ffxiv-benchmark-launcher/assets/51497231/b02df2d2-d404-493b-b4ff-64e0ffd81e65)

In the terminal, these messages appear,
```
01d8:fixme:dbghelp:elf_search_auxv can't find symbol in module
021c:fixme:ver:GetCurrentPackageId (00007F4D7784FF50 0000000000000000): stub
01c8:fixme:thread: NtSetInformationThread ThreadIdealProcessor stub!
```
The `elf_search_auxv` and `NtSetInformationThread` errors are printed multiple times.

Just in case, here are my specs.
Ubuntu 20.04.6 
AMD Ryzen 7 3700X
NVIDIA GeForce RTX 2060 SUPER
Wine 9.0

If any more information is needed, please let me know. Sorry, if I miss anything since this is my first issue post.

**Comment by hilts-vaughan** [comment]
You should be using the benchmark you downloaded, not an `xlcore` folder. Get the benchmark from https://na.finalfantasyxiv.com/benchmark/.

**Comment by MjAdrian** [comment]
I see, my apologies. I thought when it said it needed `ffxiv_dx11.exe` it meant the actual games exe file. That was the issue.
